- name: Ensure directory for APT repository keys exists
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
  - install
  - azure
  - func

- name: Download Microsoft Azure signing key
  become: true
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft-azure.asc
    mode: '0644'
  tags:
  - install
  - azure
  - func

- name: Add Microsoft Azure APT repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft-azure.asc] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_distribution_release }}-prod {{ ansible_distribution_release }} main"
    state: present
    filename: microsoft-azure
  tags:
  - install
  - azure
  - func

- name: Install az function core tools
  become: true
  apt:
    name: ["azure-functions-core-tools-4"]
    update_cache: yes
  tags:
    - install
    - azure
    - func

- name: Ensure directory for APT repository keys exists (Azure CLI)
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
  - install
  - azure
  - cli

- name: Download Microsoft Azure CLI signing key
  become: true
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft-azure-cli.asc
    mode: '0644'
  tags:
  - install
  - azure
  - cli

- name: Add Azure CLI APT repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft-azure-cli.asc] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
    filename: azure-cli
  tags:
  - install
  - azure
  - cli

- name: Install Azure CLI
  become: true
  apt:
    name: azure-cli
    state: present
    update_cache: yes
  tags:
  - install
  - azure
  - cli


