- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags:
  - install
  - node

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
  - install
  - node

- name: Install N
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  shell: n stable 
  become: true
  tags:
    - install
    - node
