- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "tldr", "ripgrep"]
  tags:
    - install
    - productivity

- name: Delete content & directory
  file:
    state: absent
    path: ~/.tmux/plugins/tpm
  tags:
    - install
    - productivity

- name: Install tpm
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  tags:
    - install
    - productivity

- name: Install CopyQ clipboard manager
  become: true
  apt:
    name: copyq
    state: present
  tags:
    - install
    - productivity
